server:
  port: 2003
spring:
  application:
    name: cloud-alibaba-seata-account
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 2d454675-4afe-4d33-a3e6-6f68f27d375d
        group: SEATA_GROUP
#      config:
#        server-addr: localhost:8848
#        file-extension: yaml
  datasource:
    #数据源连接配置
    url: jdbc:mysql://localhost:3306/seata_account?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #默认就是true 开启驼峰命名
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      namespace: 2d454675-4afe-4d33-a3e6-6f68f27d375d
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: 2d454675-4afe-4d33-a3e6-6f68f27d375d
  service:
    vgroup-mapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false
