server:
  port: 8100
spring:
  application:
    name: cloud-hystrix-payment-service
  zipkin:
    base-url: http://localhost:9411  # 推送到zipkin
  sleuth:
    sampler:
      probability: 1   #采样率   0 到1之间的数字  1最大
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #服务端url
  instance:
    instance-id: paymentHystrix8100
    prefer-ip-address: true  #显示IP
