server:
  port: 8890
spring:
  application:
    name: cloud-stream-rabbitmq-send
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment: #
            spring:
              rabbitmq:
                host: localhost
                username: guest
                password: guest
      bindings:
        output: #通道的名称
          destination: testExchange #表示要使用的exchange名称的定义
          content-type: application/json
          binder: defaultRabbit
eureka:
  client:
    register-with-eureka: true   #注册
    fetch-registry: true   #是否从eureka server 已有的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #服务端url
  instance:
    instance-id: cloud-stream-rabbitmq-send
    prefer-ip-address: true  #显示IP