server:
  port: 9527
spring:
  application:
    name: cloud-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true        #开启服务发现，配置服务名称进行动态路由
      routes:
        - id: payment_route                # 路由的id,没有规定规则但要求唯一,建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址，满足断言条件会路由到此地址 格式：lb://服务名
          predicates:                    #断言，可以编写多个，需要同时满足才能进行路由
            - Path=/consumer/see/** #断言，路径相匹配的进行路由
#        - id: payment_route         # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          uri: http://localhost:88  #匹配后提供服务的路由地址，满足断言条件会路由到此地址
#          predicates:               #断言，可以编写多个，需要同时满足才能进行路由
#            - Path=/consumer/see/** #断言，路径相匹配的进行路由
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #服务端url
  instance:
    instance-id: cloud-gateway-9527
    prefer-ip-address: true  #显示IP