server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com  #eureka 服务端实例名称
  client:
    register-with-eureka: false   #不向eureka注册中心注册自己
    fetch-registry: false     #表示为注册中心  只需要维护服务实例，不需要检索服务
    #设置eureka server交互的地址(查询服务和注册服务需要依赖地址)
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: false  #关闭Eureka自我保护模式