server:
  port: 2002
spring:
  application:
    name: cloud-alibaba-seata-storage
  cloud:
    alibaba:
     seata:
       #与server配置文件中的一致
       tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
#        file-extension: yaml
  datasource:
    #数据源连接配置
    url: jdbc:mysql://localhost:3306/seata_storage?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period: 2999ms
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #默认就是true 开启驼峰命名